### ISSUE TITLE
Home Screen

### ISSUE THREAD

**Issue by shoaibhuq** [Broke-iOS-Developers/Unplanned#13]
- [x] Develop the home screen
- [x] "Find a place" button
- [x] "Favorites" button
- [x] "Previous Place" button

![image](https://user-images.githubusercontent.com/44373355/163104390-f9f25ade-e3d2-4528-89f1-7e587e26c770.png)

**Comment by rayveng1** [comment]
Starting Issue

**Comment by shoaibhuq** [comment]
PR being reviewed
